require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colourscheme")
require("user.cmp")
require("user.lsp")
require("user.fidget")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.toggleterm")
--[[ require("user.neoscroll") ]]
require("user.dapui")
require("user.lualine")
require("user.aucommands")
